name: Format

on:
  push:
    paths:
      - .github/workflows/formatter.yml
      - biome.json
      - package.json
      - bun.lock
      - src/**/*.ts
      - tests/**/*.ts

permissions:
  contents: write

jobs:
  format:
    uses: winstxnhdw/actions/.github/workflows/format-biome.yml@main
