name: Test

on:
  push:
    paths:
      - .github/workflows/main.yml
      - biome.json
      - tsconfig.json
      - package.json
      - bun.lock
      - src/**/*.ts
      - tests/**/*.ts

jobs:
  test:
    uses: winstxnhdw/actions/.github/workflows/bun.yml@main
    with:
      disable-build: true
