name: Scaffold

on:
  push:
    paths: [.github/workflows/scaffold.yml]

permissions:
  contents: write

jobs:
  create:
    uses: winstxnhdw/actions/.github/workflows/scaffold.yml@0832d473774c1447617374fce8cf68e75c50dd7f # main
