name: Scaffold

on:
  push:
    paths: [.github/workflows/scaffold.yml]

permissions:
  contents: write

jobs:
  create:
    uses: winstxnhdw/actions/.github/workflows/scaffold.yml@4d514e9cc5ee4206069ba3216a5751f08938e355 # main
