name: Scaffold

on:
  push:
    paths: [.github/workflows/scaffold.yml]

permissions:
  contents: write

jobs:
  create:
    uses: winstxnhdw/actions/.github/workflows/scaffold.yml@10339f0c31654e18c00d8c7256351ba78bcb2ef7 # main
